name: LunaEconomy
api-version: 1.21.1
version: $version
description: A feature-rich economy plugin. Part of the Luna ecosystem ^-^

author: Luna
website: https://github.com/lunaplugins/economy

main: dev.luna.economy.LunaEconomy
